### PR TITLE
adding user db functionality

### PR DESCRIPTION
**Pull request by choldgraf**
This adds functionality for pulling commit information from users as well. I also threw together a quick database-style class to prototype how we could keep track of user information (and ultimately generalize this to projects as well). I added an example to show off the kinds of stuff it could do. LMK if this works and I can implement a User Stats page for the docathon.

### CODE REVIEW

**Comment by choldgraf** [comment]
pinging @NelleV in case you didn't get this

**Comment by choldgraf** [comment]
on my computer the example generates this plot: 
image

**Comment by NelleV** [comment]
so…
No pressure at all, but the docathon website installs our master version watchtower :D

**Comment by choldgraf** [comment]
:-O hopefully this does not destroy anything then...it shouldn't...it only adds new functionality not changes existing functionality........I think.....

**Comment by choldgraf** [comment]
https://github.com/BIDS/docathon/pull/79

**Pull request merged**
